# fly.toml app configuration file generated for hackthon on 2023-09-23T01:57:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hackthon"
primary_region = "sin"

[build]

[mounts]
  source = "hackthon_volume"
  destination = "/uploads"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
